/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");
        graph.addVertex("D");
        graph.addVertex("F");
        graph.addEdge("A", "B");
        graph.addEdge("A", "D");
        graph.addEdge("B", "C");
        graph.addEdge("D", "C");
        graph.addEdge("B", "F");
        graph.addEdge("D", "F");

//        graph.toString();
        graph.breadthFirst("A");
        System.out.println("nnnnn"+graph.breadthFirst("C"));
//        graph.getnodes();
//        System.out.println(graph.getnodes());
//
//        System.out.println(graph.getAdjVertices());
//        graph.getAdjVertices("A");
//        System.out.println(graph.getAdjVertices("A"));

//        System.out.println(Arrays.asList(graph.getAdjVertices()));
//        graph.size();

    }
}
