/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzBuzzTree;

import java.util.List;

public class App {
    public static void main(String[] args) {
        Tree tr=new Tree();
        tr.root=new Node(5);
        tr.root.left=new Node(15);
        tr.root.right=new Node(2);
        tr.root.left.left=new Node(8);
        List r=tr.inOrder();
        for (Object o:r){
            System.out.println(o);
        }
        Tree res =FizzBuzzTree.fizzBuzz(tr,tr.root);
        List rr=res.inOrder();
        for (Object Obj:rr){
            System.out.println(Obj);
        }

    }
}
