/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public static void main(String[]arg) {
//        Stack stack=new Stack();
//        stack.push(5);
//        stack.push(10);
//        stack.push(15);
//        stack.push(20);
//        stack.pop();
//        stack.peek();
//        stack.show();
//        System.out.println(stack.show());
//        stack.peek();
//        System.out.println(stack.isEmpty());
//        Queue<String> new1=new Queue<>();
//        new1.enQueue("5");
//        new1.enQueue("10");
//        new1.enQueue("15");
//        System.out.println(new1.show());
//        System.out.println(new1.show());
//        System.out.println(new1.peek());
//        PseudoQueue new1=new PseudoQueue();
//        new1.enQueqe(1);
//        new1.enQueqe(2);
//        new1.enQueqe(3);
//        new1.enQueqe(4);
//        new1.enQueqe(5);
//        new1.deQueue();
//        new1.deQueue();
//        new1.deQueue();
//        new1.enQueqe(6);
//        new1.deQueue();
//        new1.deQueue();
//        new1.enQueqe(7);
//        new1.enQueqe(8);
//        System.out.println(new1.show());
        AnimalShelter dog=new AnimalShelter();
        Animal animal=new Cats();
        Animal animal1=new Dogs();
        dog.enqueue(animal);
        dog.enqueue(animal);
        dog.enqueue(animal);
        dog.enqueue(animal1);
        System.out.println(dog.deeQueue("cat"));
//        AnimalShelter cat=new AnimalShelter();
//        Animal animal1=new Dogs();
//        cat.enqueue(animal1);
//        cat.enqueue(animal1);
//        cat.enqueue(animal1);
//        cat.enqueue(animal1);
//        dog.show();
        System.out.println(dog);

    }

}
