/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void Reversesorted() {
       int[] arr={2,3,5,7,13,11};
       assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.InsertionSort(arr)));
    }

    @Test void Fewuniques() {
        int[] arr={5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.InsertionSort(arr)));
    }

    @Test void Nearlysorted() {
        int[] arr={2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.InsertionSort(arr)));
    }
}
