/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void Reversesorted() {
       int[] arr={2,3,5,7,13,11};
       assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.InsertionSort(arr)));
    }

    @Test void Fewuniques() {
        int[] arr={5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(App.InsertionSort(arr)));
    }

    @Test void Nearlysorted() {
        int[] arr={2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(App.InsertionSort(arr)));
    }

    //Code Challenge 26
    @Test void ReversesortedMergeSort() {
        int[] arr={2,3,5,7,13,11};
        App.Mergesort(arr);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr));
    }

    @Test void FewuniquesMergeSort() {
        int[] arr={5,12,7,5,5,7};
        App.Mergesort(arr);
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(arr));
    }

    @Test void NearlysortedMergeSort() {
        int[] arr={2,3,5,7,13,11};
        App.Mergesort(arr);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr));
    }


    //Code Challenge 28
    @Test void ReversesortedQuickSort() {
        int[] arr={2,3,5,7,13,11};
        App.QuickSort(arr,0,arr.length-1);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr));
    }

    @Test void FewuniquesQuickSort() {
        int[] arr={5,12,7,5,5,7};
        App.QuickSort(arr,0,arr.length-1);
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(arr));
    }

    @Test void NearlysortedQuickSort() {
        int[] arr={2,3,5,7,13,11};
        App.QuickSort(arr,0,arr.length-1);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr));
    }
}
